name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore /p:CI=true
    - name: Build
      run: dotnet build --no-restore /p:CI=true
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CI=true
